FirstBlog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index" 


  # Rails provides a routes method named resources that maps all of the conventional routes for a collection of resources, such as articles. 

  # This creates comments as a nested resource within articles. This is another part of capturing the hierarchical relationship that exists between articles and comments.


  resources :articles do
    resources :comments
  end


  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
end

FirstBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

FirstBlog/app/models/article.rb
class Article < ApplicationRecord
    #Concern
    include Visible


    #Makes association to comments
    has_many :comments, dependent: :destroy

    #If you have an instance variable @article containing an article, you can retrieve all the comments belonging to that article as an array using @article.comments.
    

    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}

    # You may be wondering where the title and body attributes are defined. Active Record automatically defines model attributes for every table column, so you don't have to declare those attributes in your model file.

#Concern used for this logic

    # VALID_STATUSES = ['public', 'private', 'archived']

    # validates :status, inclusion: { in: VALID_STATUSES }

    # def archived?
    #     status == 'archived'
    # end
end

FirstBlog/app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  # belongs_to :article, which sets up an Active Record association. 
  # makes association to article
  belongs_to :article


#Code moved to Concerns

  # VALID_STATUSES = ['public', 'private', 'archived']

  # validates :status, inclusion: { in: VALID_STATUSES }

  # def archived?
  #   status = 'archived'
  # end
end

FirstBlog/app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    #Class methods can also be added to concerns. If we want to display a count of public articles or comments on our main page, we might add a class method to Visible as follows: You can call it in the view like any class method

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

FirstBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

FirstBlog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    #Create instane variable
    @articles = Article.all 
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

FirstBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    #Each request for a comment has to keep track of the article to which the comment is attached, thus the initial call to the find method of the Article model to get the article in question.
    def create
        @article = Article.find(params[:article_id])

        #use the create method on @article.comments to create and save the comment. This will automatically link the comment so that it belongs to that particular article.
        @comment = @article.comments.create(comment_params)

        #send the user back to the original article using the article_path(@article) helper. As we have already seen, this calls the show action of the ArticlesController which in turn renders the show.html.erb template

        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
    end

    # Strong parameters 
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

FirstBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

FirstBlog/app/helpers/articles_helper.rb
module ArticlesHelper
end

FirstBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

FirstBlog/app/views/articles/_form.html.erb
<%# This is a partial, shared view%>
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>

    <%# The full_messages_for method returns an array of user-friendly error messages for a specified attribute. If there are no errors for that attribute, the array will be empty. %>

    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> <br>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %> <br>
    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

  </div> <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

FirstBlog/app/views/articles/edit.html.erb
<h1> New Article </h1>

<%# A partial's filename must be prefixed with an underscore, e.g. _form.html.erb. But when rendering, it is referenced without the underscore, e.g. render "form". %>

<%= render "form", article: @article %>

FirstBlog/app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

FirstBlog/app/views/articles/new.html.erb
<h1> New Article </h1>

<%# A partial's filename must be prefixed with an underscore, e.g. _form.html.erb. But when rendering, it is referenced without the underscore, e.g. render "form". %>

<%= render "form", article: @article %>

FirstBlog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %> </p>

 <ul>
    <li><%= link_to "Articles", root_path %></li>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>

    <%# We use the data option to set the data-turbo-method and data-turbo-confirm HTML attributes of the "Destroy" link. Both of these attributes hook into Turbo, which is included by default in fresh Rails applications. data-turbo-method="delete" will cause the link to make a DELETE request instead of a GET request. data-turbo-confirm="Are you sure?" will cause a confirmation dialog to appear when the link is clicked. If the user cancels the dialog, the request will be aborted. %>
    <li><%= link_to "Destroy", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                        } %> 
    </li>
</ul>   
<h2>Comments</h2>

<%# Render the partial instead %>
<%# The @article object is available to any partials rendered in the view because we defined it as an instance variable. %>
<%= render @article.comments %>

<h2> Add A Comment: </h2>
<%= render 'comments/form' %>

FirstBlog/app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment: </strong>
        <%= comment.body %>
    </p>

    <p>
        <%= link_to "Destroy Comment", [comment.article, comment] , data: 
        {   
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
    </p>
<% end %>

FirstBlog/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

FirstBlog/app/views/comments/show.html.erb
<h1><%= @article.title %>

<p><%= @article.body %></p>


<ul>
    <li><%= link_to "Edit", edit_article_path(@article) %> </li>
    <li><%= link_to "Destroy", article_path(@article), data: {
        turbo_method :delete,
        turbo_confirm :"Are you sure?"
    } %>
    </li>
</ul>

<h2>Add A Comment:</h2>
<%= form_with model: [@article, @article.comments.build] do |form| %>

    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

FirstBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>